# Render Deployment Configuration
services:
  - type: web
    name: nikalosafe-backend
    env: node
    plan: free
    buildCommand: npm install && npm run db:generate && npm run db:push
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: nikalosafe-db
          property: connectionString
      - key: PORT
        value: 10000
    healthCheckPath: /
